### ISSUE TITLE
Help，Compilation issues

### ISSUE THREAD

**Issue by MADS391667** [tub-rip/event_based_bos#3]
python3 bos_event.py --config_file ./configs/hot_plate1.yaml --eval

python3: can't open file 'bos_event.py': [Errno 2] No such file or directory

**Comment by shiba24** [comment]
Hi @MADS391667 , I just released the script `bos_event.py`. You can check it.

**Comment by MADS391667** [comment]
> 嗨，我刚刚发布了剧本。你可以检查一下。`bos_event.py`

Thank you.
I noticed that you provided bos_enent.py; But when compiling, I noticed:
File "bos_event. py", line 18, in<module>
From src import data_loader, frame_flow_estimator, solver, utils, visualizer, event_image converter
I found that the utils and visualizer files are missing from the src file.

**Comment by shiba24** [comment]
I'm working to release the remaining parts of the code. Sorry for the delay. I keep this issue open for now.

**Comment by MADS391667** [comment]
> 我正在努力发布代码的其余部分。很抱歉耽搁了。我现在保持这个问题的开放性。

Thank you, I will pay attention to this issue
