### ISSUE TITLE
types.py missing?

### ISSUE THREAD

**Issue by JonathanRoos** [tub-rip/event_based_bos#4]
Multiple files try to use "types.py," (such as in "warp.py" with the line "from .types import FLOAT_TORCH, NUMPY_TORCH, is_numpy, is_torch, nt_max, nt_min"), but I cannot find the "types.py" file uploaded. Would it be possible to get access to this file?

**Comment by shiba24** [comment]
Just pushed `types` as well as `costs`. Could you try it now?

**Comment by JonathanRoos** [comment]
Thank you! It looks like __init__.py in costs is expecting to import a "flow_norm" file, but I cannot find it.

**Comment by shiba24** [comment]
Added it now!

**Comment by shiba24** [comment]
@JonathanRoos does it work now?

**Comment by shiba24** [comment]
It should be running now according to #5

**Comment by JonathanRoos** [comment]
Yes! Sorry for the delay. I can also confirm this works on Windows 11. I tested on the hot_plate1 example files provided.
