### ISSUE TITLE
third_party missing?

### ISSUE THREAD

**Issue by LvZhenH** [tub-rip/event_based_bos#5]
Hi, I ran the code and got the following error：
 
Traceback (most recent call last):
  File "...\bos_event.py", line 18, in <module>
    from src import data_loader, frame_flow_estimator, solver, utils, visualizer, event_image_converter
  File "...\src\frame_flow_estimator.py", line 20, in <module>
    from .third_party.flow_former.core.utils.utils import InputPadder
ModuleNotFoundError: No module named 'src.third_party'

**Comment by shiba24** [comment]
I think you do not need this, as these are for FlowFormer, RIFE, etc. I will delete the corresponding code.

**Comment by shiba24** [comment]
@LvZhenH please check it now, I deleted.

**Comment by LvZhenH** [comment]
Thanks you. It can run on Win 11 now.

**Comment by shiba24** [comment]
Great, thanks!
