### ISSUE TITLE
module 'openpiv.windef' has no attribute 'Settings'

### ISSUE THREAD

**Issue by matx93** [tub-rip/event_based_bos#6]
Hello.
On the first run I have got the following errors：

Traceback (most recent call last):

\event_based_bos-main\bos_event.py:18
from src import data_loader, frame_flow_estimator, solver, utils, visualizer, event_image_converter

event_based_bos-main\src\data_loader_init_.py:8
from .base import DataLoaderBase

\event_based_bos-main\src\data_loader\base.py:6
from .. import utils

\event_based_bos-main\src\utils_init_.py:1
from .config_utils import load_config_openpiv, parse_args, propagate_config, save_config

\event_based_bos-main\src\utils\config_utils.py:118
) -> windef.Settings:

AttributeError: module 'openpiv.windef' has no attribute 'Settings'

My current version of OpenPIV is 0.25.3

**Comment by matx93** [comment]
Hello.
On the first run I have got the following errors：

Traceback (most recent call last):

 \event_based_bos-main\bos_event.py:18
    from src import data_loader, frame_flow_estimator, solver, utils, visualizer, event_image_converter

event_based_bos-main\src\data_loader\__init__.py:8
    from .base import DataLoaderBase

\event_based_bos-main\src\data_loader\base.py:6
    from .. import utils

\event_based_bos-main\src\utils\__init__.py:1
    from .config_utils import load_config_openpiv, parse_args, propagate_config, save_config

\event_based_bos-main\src\utils\config_utils.py:118
    ) -> windef.Settings:

AttributeError: module 'openpiv.windef' has no attribute 'Settings'

**Comment by shiba24** [comment]
Hi @matx93 , I think the newest OpenPIV version is not compatible anymore. Could you try using `0.24.2`?
Also, I believe openpiv's module is necessary only when you want to calculate the GT flow (from frames). If you are trying to run only event-based Schlieren part, then you could comment out the openpiv import in this codebase.
